version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=False 