name: CD Pipeline

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: List directories (for debugging)
      run: |
        echo "Repository structure:"
        ls -la
        echo "Frontend directory:"
        ls -la frontend/
        echo "Public directory:"
        ls -la frontend/public/
    
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: sai4712/pr-assistant-backend:latest
        cache-from: type=registry,ref=sai4712/pr-assistant-backend:latest
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.ci
        push: true
        tags: sai4712/pr-assistant-frontend:latest
        cache-from: type=registry,ref=sai4712/pr-assistant-frontend:latest 